### ISSUE TITLE
Change the field titled "Civilization" to "Culture"

### ISSUE THREAD

**Issue by rcastong** [sfu-dhil/digital-mary#9] opened 2020-09-16 17:58 UTC
The PI requested a field name to be changed via email. Change the field titled "Civilization" to "Culture"

![image](https://user-images.githubusercontent.com/57373524/93374268-50ac0180-f80b-11ea-8f3c-15759293f8a4.png)

**Comment by joeytakeda** [comment] 2020-09-16 22:06
This looks to be a duplicate of #8, so closing this one.

**Closed as completed by joeytakeda** 2020-09-16 22:06 UTC
